name: appx
description: tools and extension for any flutter app
version: 0.0.1
homepage: "none"

publish_to: "none"

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # routing
  auto_route: ^5.0.1

  bloc_error_handler:
    git: https://github.com/masreplay/bloc_error_handler.git

  # fonts
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1
  google_fonts: ^3.0.1

  # data-network
  retrofit: ^3.3.1
  logger: ^1.1.0
  awesome_dio_interceptor: ^0.0.2+3
  error_handler: ^1.1.0
  dio: ^4.0.6

  # data-model
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  # data-local
  isar: ^3.0.2
  shared_preferences: ^2.0.15

  # data-paging
  infinite_scroll_pagination: ^3.2.0

  # data-state-management
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3

  # platform
  universal_platform: ^1.0.0+1

  # link
  url_launcher: ^6.1.5

  # map
  google_maps_flutter: ^2.2.1

  # ui
  extra_alignments: ^1.0.0+1
  flextras: ^0.0.2
  gap: ^2.0.0
  animations: ^2.0.2
  flutter_animate: ^1.0.0
  flutter_svg: ^1.1.5
  badges: ^2.0.3
  flutter_native_splash: ^2.2.14
  image_picker: ^0.8.6
  cached_network_image: ^3.2.2
  timeago: ^3.3.0
  readmore: ^2.2.0

  # phone number
  intl_phone_field: ^3.1.0
  sms_autofill: ^2.2.0

  # validation
  form_validator: ^1.0.2

  # auth provider
  google_sign_in: ^5.4.2

  # utility
  intl: ^0.17.0
  adaptive_breakpoints: ^0.1.4
  flutter_kurdish_localization: ^1.0.1
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_analytics: ^10.0.6

  share: ^2.0.4
  floating_draggable_widget: ^2.1.2

  json_viewer:
    path: ../json_viewer

dev_dependencies:
  injectable_generator: ^1.5.4
  auto_route_generator: ^5.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  retrofit_generator: ">=4.0.0 <5.0.0"
  icon_font_generator: ^3.2.0
  isar_generator: ^3.0.5
  isar_flutter_libs: ^3.0.5
