name: appx
description: tools and extension for any flutter app
version: 0.0.1
homepage: "none"

publish_to: "none"

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # routing
  auto_route: ^5.0.4

  # fonts
  cupertino_icons: ^1.0.5

  # data-network
  retrofit: ^3.3.1
  error_handler: ^1.1.0
  dio: ^4.0.6

  # data-model
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  # data-local
  isar: ^3.0.5
  shared_preferences: ^2.0.15

  # data-paging
  infinite_scroll_pagination: ^3.2.0

  # data-state-management
  flutter_bloc: ^8.1.1

  # platform
  universal_platform: ^1.0.0+1

  # link
  url_launcher: ^6.1.7
  share: ^2.0.4

  # ui
  image_picker: ^0.8.6

  # phone number
  intl_phone_field: ^3.1.0

  # validation
  form_validator: ^2.1.1

  # utility
  intl: ^0.17.0
  adaptive_breakpoints: ^0.1.4
  injectable: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  retrofit_generator: ">=4.0.0 <5.0.0"
  isar_generator: ^3.0.5
  isar_flutter_libs: ^3.0.5
